#+TITLE: Lantern

* Overview
The goal of this project is to create a set of functions that make
exploratory data analysis with common lisp fun and easy. The function
will provide some default behavior for more powerful common lisp libraries:
 - io :: data input and output from to data base
   - using cl-csv, cl-sql
 - tidy :: data manipulation
   - using group-by, alexandria
 - plot :: summary graphs
   - using eazy-gnuplot
 - stats :: summary statistics
   - using lhstats and alexandria

The end result should allow the user to load some data, quickly
manipulate, summarize and visualize.

* Approach
The approach is inspired by clojure incanter, except there will not be a
data-set structure. Instead, lists of p-lists (lopl) will be used to manipulate data.

* Todo
Everything, but here is the initial wish list
** io [0/1]
Functions to create a list of p-lists (lopl)
- [ ] convert strings to numbers when loaded
** tidy [0/5]
Functions to manipulate  a lopl
- [ ] filter rows
- [ ] select columns
- [ ] aggregate
- [ ] transform
- [ ] sort
** stats [0/1]
- [ ] frequency
** plots [0/7]
- [ ] bar chart
- [ ] histogram
- [ ] density plot
- [ ] scatter plot
- [ ] box plot
- [ ] cumsum plot
- [ ] timeseries plot
